# Generated by Django 4.2.26 on 2026-05-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('zone', models.CharField(max_length=100)),
                ('tuteur', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_identite', models.CharField(max_length=50, unique=True)),
                ('type_aide', models.CharField(choices=[('Alimentaire', 'Alimentaire'), ('Cash', 'Cash'), ('Médical', 'Médical'), ('WASH', 'WASH'), ('Éducation', 'Éducation')], max_length=20)),
                ('uuid_blockchain', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
