# Generated by Django 4.2.26 on 2026-05-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='genre',
            field=models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='type_aide',
            field=models.CharField(blank=True, choices=[('Alimentaire', 'Alimentaire'), ('Cash', 'Cash'), ('Médical', 'Médical'), ('WASH', 'WASH'), ('Éducation', 'Éducation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='uuid_blockchain',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
